# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.16-fpm-buster # Debian GNU/Linux 10 (buster)
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql_circle_testing

      # - image: circleci/mysql:5.7.33
      #   environment:
      #     - MYSQL_ALLOW_EMPTY_PASSWORD: true
      #     - MYSQL_DATABASE: circle_test

    working_directory: ~/application

    steps:
      - checkout

      - run:
          command: echo "Hello ${CIRCLE_USERNAME}"
      - run:
          command: |-
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
          name: 一部の CircleCI ランタイム環境変数の表示
      - run:
          command: |-
            echo "uname:" $(uname -a)
            echo "arch: " $(arch)
          name: システム情報の表示

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      # Install PHP Extension
      - run: sudo docker-php-ext-install pdo_mysql

      # npm
      - run:
          name: "Node.js と npm の更新"
          command: |
            curl -sSL "https://nodejs.org/dist/v11.10.0/node-v11.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v11.10.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      - run:
          name: "node -v npm -v"
          command: |
            node -v
            npm -v
      - restore_cache:
          keys:
            - v1-node-{{ checksum "package.json" }}
            - v1-node-
      - run: npm install
      - save_cache:
          key: v1-node-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # composer Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # - run:
      #     name: "artisan db"
      #     command: |
      #       php artisan migrate

      - run: rm -rf ./tests/imo/
      - run:
          name: "Run PHPUnit"
          command: |
            vendor/bin/phpunit --log-junit phpunit.xml -v tests/Feature/ExampleTest.php

      - run:
          name: "view test log"
          command: tail -n 100 ./storage/logs/laravel.log
          when: always

      - run:
          name: "view test logg"
          command: cat tests/imo/ttt.txt
          when: always
